<script>
    import Gallery from '$lib/components/Gallery.svelte';
    import GalleryItem from '$lib/components/GalleryItem.svelte';


    // TODO: use TS bindings generated by ts-rs
    export let data;
    let { posts } = data;
</script>

<div class="main-container">
    <h1>Home page</h1>
    {#each posts as post}
        <Gallery>
            <GalleryItem imageUrl={`https://pub-57f47fc2081648efaa3f351802d15c5d.r2.dev/${post.image.path}`} />
        </Gallery>
        <br/>
    {/each}
</div>

<style>
.main-container {
    max-width: 1250px;
    margin: 0px auto;
}
</style>