<script>
    // TODO: use TS bindings generated by ts-rs
    export let data;
    let { posts } = data;
</script>

<div>
    <h1>Home page</h1>
    {#each posts as post}
        <div>title: {post.title}</div>
        <div>content: {post.content}</div>
        <!-- TODO: check for a better way than making the bucket public -->
        <!-- TODO: fix opening the image in a new tab -->
        <img class="post-image" src={`https://pub-57f47fc2081648efaa3f351802d15c5d.r2.dev/${post.image.path}`} alt="">
        <br/>
    {/each}
</div>

<style>
.post-image {
    max-width: 90vw;
}
</style>