<script lang="ts">
  import Gallery from "$lib/components/Gallery.svelte";
  import Navbar from "$lib/components/Navbar.svelte";
  import type { ComicResponseBrief } from '../../../bindings/ComicResponseBrief';

  // TODO: use TS bindings generated by ts-rs
  export let data: { comics: ComicResponseBrief[] };
  let { comics } = data;

  
</script>

<div class="main-container">
  <h1>Home page</h1>
  <Gallery {comics} />
  <Navbar></Navbar>
</div>

<style>
  .main-container {
    max-width: 1250px;
    margin: 0px auto;
  }
</style>
