//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11.2

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "comics_genres_mapping")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub comic_id: Uuid,
    #[sea_orm(primary_key, auto_increment = false)]
    pub genre_id: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::comic_genres::Entity",
        from = "Column::GenreId",
        to = "super::comic_genres::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    ComicGenres,
    #[sea_orm(
        belongs_to = "super::comics::Entity",
        from = "Column::ComicId",
        to = "super::comics::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Comics,
}

impl Related<super::comic_genres::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ComicGenres.def()
    }
}

impl Related<super::comics::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Comics.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
