//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11.2

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "comment_parents_children")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub parent_comment_id: Uuid,
    pub child_comment_id: Uuid,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::comments::Entity",
        from = "Column::ChildCommentId",
        to = "super::comments::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Comments2,
    #[sea_orm(
        belongs_to = "super::comments::Entity",
        from = "Column::ParentCommentId",
        to = "super::comments::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Comments1,
}

impl ActiveModelBehavior for ActiveModel {}
