//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11.2

pub use super::chapter_pages::Entity as ChapterPages;
pub use super::chapters::Entity as Chapters;
pub use super::comics::Entity as Comics;
pub use super::profile_images::Entity as ProfileImages;
pub use super::users::Entity as Users;
