//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11.2

pub use super::chapter_pages::Entity as ChapterPages;
pub use super::chapters::Entity as Chapters;
pub use super::comics::Entity as Comics;
pub use super::comment_parents_children::Entity as CommentParentsChildren;
pub use super::comments::Entity as Comments;
pub use super::profile_images::Entity as ProfileImages;
pub use super::user_roles::Entity as UserRoles;
pub use super::users::Entity as Users;
